name: "Comprobaciones básicas del cuerpo del PR"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Comprobaciones PR
      uses: JJ/github-pr-contains-action@releases/v13
      with:
        github-token: ${{github.token}}
        bodyContains: "x] NOCERRAR"
        filesChanged: 1
        linesChanged: 1

